project:
  type: book

book:
  title: "Data Analytics and Visualization"
  author: Piotr Jastrzębski
  date: today
  cover-image: aiwd.jpg
  chapters:
    - part: Introduction
      chapters: 
      - index.qmd
      - a_bit_of_theory.qmd
  downloads: pdf


format:
  html:
    theme:
      light: cosmo
      dark: solar
    lang: en
  pdf:
    lang: en
    header-includes: |
      \titlehead{\includegraphics[width=6in]{aiwd.jpg}}
    keep-tex: true




