project:
  type: book

book:
  title: "Data analysis and visualisation"
  author: Piotr Jastrzębski
  date: today
  cover-image: aiwd.jpg
  chapters:
    - part: Introduction
      chapters: 
      - index.qmd
      - a_bit_of_theory.qmd
      - configuration.qmd
    - part: NumPy
      chapters:
      - numpy_getting_started.qmd
      - list_array.qmd
      - numpy-attributes.qmd
      - numpy-datatypes.qmd
      - numpy-creating-arrays.qmd
      - numpy-indexing.qmd
      - numpy-modifications.qmd
      - numpy-broadcasting.qmd
      - numpy-ufunc.qmd
      - numpy-strings.qmd
      - numpy-linear-algebra.qmd
      - numpy-conditions.qmd
      - numpy-miscellaneous.qmd
    - part: Data exploration
      chapters:
      - exploration.qmd
    - part: "Pandas"
      chapters:
      - pandas-start.qmd
      - pandas-indexing.qmd
  downloads: [pdf, epub]
  repo-url: https://github.com/pjastr/dav-book
  repo-actions: [issue]
  
execute:
  freeze: auto



format:
  html:
    theme:
      light: cosmo
      dark: solar
    lang: en
  pdf:
    lang: en
    header-includes: |
      \titlehead{\includegraphics[width=6in]{aiwd.jpg}}
    keep-tex: true
  epub:
    lang: en
    cover-image: aiwd.jpg
    toc: true
    




