# Matplotlib - extras part 2.




## Horizontal and vertical lines

The functions `axhline` and `axvline` are used to add horizontal and vertical lines to a chart, respectively.

`axhline` draws a horizontal line passing through a specified value on the Y axis, regardless of the value on the X axis. The function syntax is `axhline(y, xmin, xmax, **kwargs)`, where:

* `y` - the value on the Y axis through which the line passes (default 0)
* `xmin`, `xmax` - values in the range 0-1 specifying the start and end of the line on the X axis (default 0 and 1)
* `**kwargs` - additional arguments, such as `color`, `linewidth`, or `linestyle`, used to control the appearance of the line

`axvline` draws a vertical line passing through a specified value on the X axis, regardless of the value on the Y axis. The function syntax is `axvline(x, ymin, ymax, **kwargs)`, where:

* `x` - the value on the X axis through which the line passes (default 0)
* `ymin`, `ymax` - values in the range 0-1 specifying the start and end of the line on the Y axis (default 0 and 1)
* `**kwargs` - additional arguments, such as `color`, `linewidth`, or `linestyle`, used to control the appearance of the line


```{python}
#| echo: true
import matplotlib.pyplot as plt

plt.plot([0, 5], [0, 5], color='blue')
plt.axhline(2, color='red', linewidth=2)  # Horizontal line passing through Y=2
plt.axvline(3, color='green', linestyle='--')  # Vertical line passing through X=3, dashed line style
plt.show(block=True)

```

In the example above, `axhline` draws a red horizontal line passing through the value 2 on the Y axis, while `axvline` draws a green dashed vertical line passing through the value 3 on the X axis.

```{python}
#| echo: true
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(-5, 5, 0.1)
x1 = x[x < 0]
y1 = 1 / x1
plt.plot(x1, y1)
x2 = x[x > 0]
y2 = 1 / x2
plt.plot(x2, y2)
plt.ylim(-10, 10)
plt.axhline(y=0, linestyle="--")
plt.axvline(x=0, linestyle=":")
plt.show(block=True)

```

## Annotations (text) on a chart

The `annotate` function is used to add annotations (text and arrows) to a chart in order to highlight or mark specific points or areas.

The function syntax is `annotate(text, xy, xytext, arrowprops, **kwargs)`, where:

- `text` - a string representing the annotation text.
- `xy` - a tuple (x, y) specifying the coordinates of the point referred to in the annotation.
- `xytext` - a tuple (x, y) specifying the coordinates at which the annotation text should begin. If not provided, the text will be displayed directly at the `xy` coordinates.
- `arrowprops` - a dictionary containing options for drawing the arrow, such as `arrowstyle`, `color`, or `linewidth`. If not provided, the arrow will not be drawn.
- `**kwargs` - additional arguments for text formatting, such as `fontsize`, `color`, or `fontweight`.


```{python}
#| echo: true
import matplotlib.pyplot as plt

plt.plot([1, 2, 3, 4], [2, 4, 9, 16], marker='o', linestyle='-', color='blue')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')

plt.annotate('Important point (2, 4)',
             xy=(2, 4),                           # Coordinates of the point to mark
             xytext=(2.5, 6),                     # Coordinates of the start of the text
             arrowprops=dict(facecolor='red'),    # Arrow properties (color)
             fontsize=12,                         # Font size
             color='blue',                        # Text color
             fontweight='bold')                   # Font weight

plt.show(block=True)

```

If you want to add an annotation with text only, the function syntax is `annotate(text, xy, **kwargs)`, where:

- `text` - a string representing the annotation text.
- `xy` - a tuple (x, y) specifying the coordinates at which the annotation text should begin.
- `**kwargs` - additional arguments for text formatting, such as `fontsize`, `color`, `fontweight`, or `horizontalalignment`.


```{python}
#| echo: true
import matplotlib.pyplot as plt

plt.plot([1, 2, 3, 4], [2, 4, 9, 16], marker='o', linestyle='-', color='blue')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')

plt.annotate('Important point (2, 4)',
             xy=(2, 4),                           # Coordinates of the start of the text
             fontsize=12,                         # Font size
             color='blue',                        # Text color
             fontweight='bold',                   # Font weight
             horizontalalignment='right')         # Right-align the text

plt.show(block=True)

```

## Axis labels

The functions `xlabel` and `ylabel` are used to add labels to the X and Y axes on a chart, respectively. Axis labels help to better understand the presented data by indicating what values are represented on each axis.

The function syntax is `xlabel(label, **kwargs)` or `ylabel(label, **kwargs)`, where:

- `label` - a string representing the axis label text.
- `**kwargs` - additional arguments for label formatting, such as `fontsize`, `color`, `fontweight`, or `horizontalalignment`.


```{python}
#| echo: true
import matplotlib.pyplot as plt

x = [1, 2, 3, 4]
y = [2, 4, 6, 8]

plt.plot(x, y, marker='o', linestyle='-', color='blue')

plt.xlabel('X axis', fontsize=12, color='red', fontweight='bold')
plt.ylabel('Y axis', fontsize=12, color='green', fontweight='bold')

plt.show(block=True)

```

The `annotate` function allows the use of LaTeX syntax in the annotation text, which is especially useful when we want to add mathematical equations or symbols to a chart. To use LaTeX syntax, the text must be placed between dollar signs (`$`).


```{python}
#| echo: true
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 2 * np.pi, 100)
y = np.sin(x)

plt.plot(x, y)
plt.xlabel('x')
plt.ylabel('sin(x)')

# Annotation with text in LaTeX syntax
plt.annotate(r'$\sin(\frac{2\pi}{3})=\frac{\sqrt{3}}{2}$',
             xy=(2 * np.pi / 3, np.sqrt(3) / 2),  # Coordinates of the point to mark
             xytext=(3, 1.0),                     # Coordinates of the start of the text
             fontsize=12,                         # Font size
             arrowprops=dict(facecolor='red'),    # Arrow properties (color)
             bbox=dict(facecolor='white'))        # Box around the text (background color)

plt.show(block=True)

```



## Axis tick labels

The functions `xticks` and `yticks` are used to manipulate the labels of the X and Y axes and the values on the axis, respectively. They allow you to control the display of labels, the spacing between them, and the formatting.

`xticks` manipulates the labels and values on the X axis, and `yticks` on the Y axis. The function syntax is `xticks(ticks, labels, **kwargs)` or `yticks(ticks, labels, **kwargs)`, where:

- `ticks` - a list of values for which labels are to be placed on the axis. If not provided, the current values remain.
- `labels` - a list of strings to be used as labels for the values from the `ticks` list. If not provided, the default labels will be used.
- `**kwargs` - additional arguments for label formatting, such as `fontsize`, `color`, `fontweight`, or `rotation`.


```{python}
#| echo: true
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(0, 10, 0.1)
y = np.sin(x)

plt.plot(x, y)

xtick_vals = [0, np.pi, 2 * np.pi, 3 * np.pi]
xtick_labels = ['0', r'$\pi$', r'$2\pi$', r'$3\pi$']

ytick_vals = [-1, -0.5, 0, 0.5, 1]
ytick_labels = ['-1', '-1/2', '0', '1/2', '1']

plt.xticks(xtick_vals, xtick_labels, fontsize=12, color='red')
plt.yticks(ytick_vals, ytick_labels, fontsize=12, rotation=45)

plt.show(block=True)

```


```{python}
#| echo: true
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(-3, 3, 0.1)
y = x ** 2 + 2 * x
plt.plot(x, y)
plt.annotate(xy=(-1, 5), text="something")
plt.xticks([-2, 1, 2], color="red")
plt.ylabel("abc", color="green")
plt.show(block=True)

```

## Grid

The `grid` function allows you to add a grid to a chart, which makes it easier to assess values on the axes and compare them. You can control the color, width, and style of the grid lines, as well as specify which axes should have a grid.

The function syntax is `plt.grid(b=None, which='major', axis='both', **kwargs)`, where:

- `b` - a boolean value (True/False) that determines whether the grid is to be displayed. Set to `None` by default, which means that Matplotlib automatically determines whether the grid should be displayed based on the configuration.
- `which` - specifies which grid lines are to be displayed: 'major' (only grid lines for major ticks), 'minor' (grid lines for minor ticks), or 'both' (default - grid lines for both types of ticks).
- `axis` - specifies which axes should have a grid: 'both' (both axes), 'x' (only the X axis), or 'y' (only the Y axis).
- `**kwargs` - additional arguments for grid formatting.


```{python}
#| echo: true
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 2 * np.pi, 100)
y = np.sin(x)

# Creating the chart
plt.plot(x, y, color='blue', linewidth=2)

# Adding the grid
plt.grid(True, which='both', color='gray', linewidth=0.5, linestyle='--')

# Adding a title and axis labels
plt.title('Plot of the function sin(x)')
plt.xlabel('x')
plt.ylabel('sin(x)')

# Displaying the chart
plt.show(block=True)

```


```{python}
#| echo: true
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, np.pi * 2, 100)
plt.subplot(3, 1, 1)
plt.plot(x, np.sin(x), 'r')
plt.grid(True)
plt.xlim(0, np.pi * 2)
plt.subplot(3, 1, 2)
plt.plot(x, np.cos(x), 'g')
plt.grid(True)
plt.xlim(0, np.pi * 2)
plt.subplot(3, 1, 3)
plt.plot(x, np.sin(x), 'r', x, np.cos(x), 'g')
plt.grid(True)
plt.xlim(0, np.pi * 2)
plt.tight_layout()
plt.savefig("fig3.png", dpi=72)
plt.show(block=True)

```
