# NumPy - Getting Started

NumPy is a Python library for scientific computing.

Applications:
  
* linear algebra
* advanced mathematical (numerical) computations
* numerical integration
* solving equations



## Importing the NumPy library

```python
import numpy as np
```

The fundamental object in the NumPy library is an N-dimensional array called `ndarray`. Each element of the array is treated as a `dtype` type.


```python
np.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
```

* object - an object (or sequence) to be converted into an array
* dtype - type
* copy - whether objects should be copied, default is `True`
* order - memory layout: C (rows), F (columns), A, K
* subok - handled by subclasses (if `True`), default is `False`
* ndmin - minimum number of dimensions of the array
* like - creation based on a reference array



```{python}
#| echo: true
import numpy as np

a = np.array([1, 2, 3])    # <1>                           
print("a:", a) 
print("type of a:", type(a))  # <2>
b = np.array([1, 2, 3.0]) # <3>
print("b:", b)
c = np.array([[1, 2], [3, 4]]) # <4>
print("c:", c)
d = np.array([1, 2, 3], ndmin=2) # <5>
print("d:", d)
e = np.array([1, 2, 3], dtype=complex) # <6>
print("e:", e)
f = np.array(np.asmatrix('1 2; 3 4')) # <7>
print("f:", f)
g = np.array(np.asmatrix('1 2; 3 4'), subok=True) # <8>
print("g:", g)
print(type(g))

```

1. Creating an array with default settings.
2. Checking the type.
3. One of the elements is of a different type. Therefore, upcasting to the "largest" type occurs.
4. Here we get a 2x2 array.
5. In this line we get an array with dimensions 1x3 (shape `(1, 3)`).
6. Forcing the `complex` type — a type with a wider range.
7. Using the matrix subtype.
8. Preserving the matrix type.
